name: flutter_bluetooth_serial
description: Flutter basic serial port Bluetooth (HC-05) for Android
version: 0.4.0
flutter:
  plugin:
    platforms:
      android:
        package: io.github.edufolly.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin
environment:
  sdk: ">=2.12.0 <3.0.0"
